### PR TITLE
Ignore bad formated characters on serial line

### PR DESCRIPTION
**Pull request by Cyril-Roques**

### CODE REVIEW

**Comment by youtux** [comment]
I think you may want to PR this to the official repo: https://github.com/faucamp/python-gsmmodem

**Comment by Cyril-Roques** [comment]
Sure but the official repo has not the python3 stuff, yours has it, so maybe you could send a PR to the official repo with your python3 commit ?

**Comment by youtux** [comment]
I’m sorry but I’m no longer maintaining this fork. Feel free to PR to the official one with my changes.

**Comment by Cyril-Roques** [comment]
Ok no problems,
Thanks

**Pull request closed without merging**
